name: Deploy via Uncloud
description: Deploy Docker images via Uncloud.
author: thatskyapplication
branding:
  icon: cloud
  color: black
inputs:
  image-tag:
    description: Docker image tag to deploy.
    required: true
  uncloud-profile:
    description: One or more profiles to enable (space-separated).
    required: false
  compose-files:
    description: One or more Compose files (space-separated).
    required: true
  ssh-private-key:
    description: SSH private key for server access.
    required: true
  server-user:
    description: SSH username for the server.
    required: true
  server-host:
    description: Server hostname.
    required: true
  recreate:
    description: Recreate containers even if their configuration and image haven't changed.
    required: false
    default: "false"
  version:
    description: Version to use for the Uncloud CLI.
    required: false
runs:
  using: composite
  steps:
    - name: Install Uncloud CLI
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: curl --fail --show-error --silent https://get.uncloud.run/install.sh | sh

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Add server to known hosts
      shell: bash
      env:
        SERVER_HOST: ${{ inputs.server-host }}
      run: ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

    - name: Push image to server
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
        SERVER_USER: ${{ inputs.server-user }}
        SERVER_HOST: ${{ inputs.server-host }}
      run: uc image push "$IMAGE_TAG" --connect "$SERVER_USER@$SERVER_HOST"

    - name: Deploy via Uncloud
      shell: bash
      env:
        SERVER_USER: ${{ inputs.server-user }}
        SERVER_HOST: ${{ inputs.server-host }}
        COMPOSE_FILES: ${{ inputs.compose-files }}
        UNCLOUD_PROFILE: ${{ inputs.uncloud-profile }}
        RECREATE: ${{ inputs.recreate }}
      run: |
        DEPLOY_ARGS=(--connect "$SERVER_USER@$SERVER_HOST")

        for file in $COMPOSE_FILES; do
          DEPLOY_ARGS+=(--file "$file")
        done

        if [ -n "$UNCLOUD_PROFILE" ]; then
          DEPLOY_ARGS+=(--profile "$UNCLOUD_PROFILE")
        fi

        if [ "$RECREATE" = "true" ]; then
          DEPLOY_ARGS+=(--recreate)
        fi

        DEPLOY_ARGS+=(--yes)

        uc deploy "${DEPLOY_ARGS[@]}"
